### ISSUE TITLE
Сбор метрик

### ISSUE THREAD

**Issue by Konohomaru** [Konohomaru/Gira#10]
Программным путём подсчитать метрики реального репозитория и начать возвращать их в API. Для начала можно реализовать самым наивным способом.

### DoD:

1. Можно получить Sprint Velocity, Sprint Burndown и Task Cycle Time.
2. ~~Можно получать обрабатываемые задачи.~~
3. ~~Можно получать проекты репозитория.~~

**Comment by DmitriiKozhevnikov** [comment]
Загружай код в репу на ревью 👍

**Comment by Konohomaru** [comment]
Проститировать на ГитХаб проекте "Доска"
