### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by DmitriiKozhevnikov** [Konohomaru/Gira#19]
- [x] SprintDay в нодах статистик - это же просто календарный день? откуда спринт в названии
- [x] ProjectComparer надо бы переделать в реализацию IComparable у Project + overload =<> (кажется, можно просто воспользоваться record'ом)
- [x] не очень понятна регистрация  в контейнере доменных сущностей - чтобы что? 
- [x] в домен подмешаны другие слои приложения
   - конфигурацию аппхоста следует вынести в отдельный модуль или перенести в вебапи, тк это не часть доменной модели
   - доменная модель зависит от гитхаба через компарер и гитхабдатасорс, это зависимости быть не должно, доменная модель - это только про бизнес
   - репо - это тоже не совсем часть домена, скорее про интеграцию гитхаба, в домене есть команда и проект
   - sprints data source - тоже другой слой приложения  (ближе к persistence)
- [x] не понял смысла partial классов в github (год класс? разбить на клиент и фасад?)
- [x] почистить проект от неиспользуемых методов и грамматических ошибок
- [x] тестики? на домен и гитхаб, кажется, можно сразу, а вот вебапи может подождать

---
ℹ️ Почитай про [Clean Architecure](https://www.dandoescode.com/blog/clean-architecture-an-introduction/)

**Comment by Konohomaru** [comment]
Не понимаю как вынести конфигурацию АппХоста. Сейчас перешёл на Майкрасовтовский контейнер и прописал соответствующее расширение.

Выпилил ГитХаб в отдельный класс `GitHubFacade`. Он используется в `ProjectsRepository`, чтобы переводить язык ГитХаба в языка Гиры. Gira или **Gi**tHub **R**epository **A**nalyzer.

**Comment by Konohomaru** [comment]
Выпилить `IGItHubFacade` в отдельный модуль "Integrations". Передовать в конфиг `GiraModel` имплементацию `IDataSource` и везде в проекте использовать её.
